### ISSUE TITLE
Issue while capturing the image 

### ISSUE THREAD

**Issue by azharuddinsayed** [jlandersen/xamarin-forms-camera#4]
After calling the method Camera.TakePicture there is no call back from the Camera class ???????????

**Comment by azharuddinsayed** [comment]
Any update regarding this issue ?????

**Comment by jlandersen** [comment]
Hi @azharuddinsayed 
I haven't touched Xamarin in over 3 years now and the platform has naturally developed since then which may cause a few trouble with this implementation If you happen to find the problem and a solution, feel free to send a PR. I am not working with Xamarin anymore and am not set up for running any Xamarin solutions at this time.
